// <auto-generated />
using System;
using EventAlbumApp.Connetion;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventAlbumApp.Migrations
{
    [DbContext(typeof(AppdbContext))]
    partial class AppdbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventAlbumApp.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2")
                        .HasColumnName("endEvent");

                    b.Property<Guid>("IdQr")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idQr");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idUser");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("names");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2")
                        .HasColumnName("startEvent");

                    b.Property<Guid?>("idQr")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("idUser")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdQr")
                        .IsUnique();

                    b.HasIndex("IdUser");

                    b.ToTable("Album", t =>
                        {
                            t.Property("idQr")
                                .HasColumnName("idQr1");

                            t.Property("idUser")
                                .HasColumnName("idUser1");
                        });
                });

            modelBuilder.Entity("EventAlbumApp.Entities.Photos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Data")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("datas");

                    b.Property<Guid>("IdAlbum")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("idAlbum");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("idAlbum")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdAlbum");

                    b.ToTable("Photos", t =>
                        {
                            t.Property("idAlbum")
                                .HasColumnName("idAlbum1");
                        });
                });

            modelBuilder.Entity("EventAlbumApp.Entities.Qr", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("Token")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Token");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Qr");
                });

            modelBuilder.Entity("EventAlbumApp.Entities.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("names");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("surname");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EventAlbumApp.Entities.Album", b =>
                {
                    b.HasOne("EventAlbumApp.Entities.Qr", "Qr")
                        .WithOne("Album")
                        .HasForeignKey("EventAlbumApp.Entities.Album", "IdQr")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventAlbumApp.Entities.Users", "Users")
                        .WithMany("Albums")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Qr");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EventAlbumApp.Entities.Photos", b =>
                {
                    b.HasOne("EventAlbumApp.Entities.Album", "Album")
                        .WithMany("Photos")
                        .HasForeignKey("IdAlbum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("EventAlbumApp.Entities.Album", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("EventAlbumApp.Entities.Qr", b =>
                {
                    b.Navigation("Album");
                });

            modelBuilder.Entity("EventAlbumApp.Entities.Users", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
